apiVersion: karectl.io/v1alpha1
kind: ResearchNetworkPolicy
metadata:
  name: asthma-network
  namespace: karectl-system
  labels:
    karectl.io/project: asthma
spec:
  project: asthma
  dataClassification: "internal"
  isolation: "standard"
  
  ciliumPolicies:
    - name: asthma-egress
      spec:
        endpointSelector:
          matchLabels:
            karectl.io/project: asthma
        egress:
          # Allow internal cluster communication
          - toEntities:
            - cluster
          # Allow DNS
          - toEndpoints:
            - matchLabels:
                k8s:io.kubernetes.pod.namespace: kube-system
                k8s:app: kube-dns
            toPorts:
            - ports:
              - port: "53"
                protocol: UDP
          # Project-specific external sites
          
